// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ssh3POGAhURGwB-RiA9i-Lk3OICEvJU',
    appId: '1:480016799711:web:840ec88c3725942c95566a',
    messagingSenderId: '480016799711',
    projectId: 'test123-d530a',
    authDomain: 'test123-d530a.firebaseapp.com',
    storageBucket: 'test123-d530a.appspot.com',
    measurementId: 'G-GZWLQ2QPCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8AW2Tl3yS7WDl5h92BPeL_z5vBzpdrLA',
    appId: '1:480016799711:android:b671d97181f9099695566a',
    messagingSenderId: '480016799711',
    projectId: 'test123-d530a',
    storageBucket: 'test123-d530a.appspot.com',
  );
}
