///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PersonalDetailEntity {
/*
{
  "name": "",
  "number": 0
} 
*/

  String? name;
  int? number;

  PersonalDetailEntity({
    this.name,
    this.number,
  });
}
