///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserEntity {
/*
{
  "name": "",
  "number": "",
  "photo": "",
  "about": ""
} 
*/

  String? name;
  String? number;
  String? photo;
  String? about;

  UserEntity({
    this.name,
    this.number,
    this.photo,
    this.about,
  });
}
